# Generated by Django 4.1.4 on 2022-12-13 21:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
            ],
        ),
    ]
