# Generated by Django 4.1.3 on 2022-12-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To-do'), ('doing', 'Doing'), ('done', 'Done')], max_length=5, verbose_name='status'),
        ),
    ]
