# Generated by Django 4.1.3 on 2022-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'À fazer'), ('doing', 'Em andamento'), ('done', 'Terminado')], default='todo', max_length=5, verbose_name='status'),
        ),
    ]
